// This file is automatically generated. DO NOT EDIT.

class AppConstants {
  static const String app_name = 'Emallbazar Driver';
  //please add your panel's API base URL here (you can find from settings->client APIs)
  static const String baseUrl = 'https://emallbazar.com/delivery_boy/app/v1/api/';// demo
  // static const String baseUrl = 'https://vendoreshop.wrteam.co.in/delivery_boy/app/v1/api/'; //dev
  static const String defaultLanguage = 'en';
}